/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PlagiarismReport } from "./PlagiarismReport";
import { PlagiarismReportCountArgs } from "./PlagiarismReportCountArgs";
import { PlagiarismReportFindManyArgs } from "./PlagiarismReportFindManyArgs";
import { PlagiarismReportFindUniqueArgs } from "./PlagiarismReportFindUniqueArgs";
import { CreatePlagiarismReportArgs } from "./CreatePlagiarismReportArgs";
import { UpdatePlagiarismReportArgs } from "./UpdatePlagiarismReportArgs";
import { DeletePlagiarismReportArgs } from "./DeletePlagiarismReportArgs";
import { Document } from "../../document/base/Document";
import { PlagiarismReportService } from "../plagiarismReport.service";
@graphql.Resolver(() => PlagiarismReport)
export class PlagiarismReportResolverBase {
  constructor(protected readonly service: PlagiarismReportService) {}

  async _plagiarismReportsMeta(
    @graphql.Args() args: PlagiarismReportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PlagiarismReport])
  async plagiarismReports(
    @graphql.Args() args: PlagiarismReportFindManyArgs
  ): Promise<PlagiarismReport[]> {
    return this.service.plagiarismReports(args);
  }

  @graphql.Query(() => PlagiarismReport, { nullable: true })
  async plagiarismReport(
    @graphql.Args() args: PlagiarismReportFindUniqueArgs
  ): Promise<PlagiarismReport | null> {
    const result = await this.service.plagiarismReport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PlagiarismReport)
  async createPlagiarismReport(
    @graphql.Args() args: CreatePlagiarismReportArgs
  ): Promise<PlagiarismReport> {
    return await this.service.createPlagiarismReport({
      ...args,
      data: {
        ...args.data,

        document: args.data.document
          ? {
              connect: args.data.document,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PlagiarismReport)
  async updatePlagiarismReport(
    @graphql.Args() args: UpdatePlagiarismReportArgs
  ): Promise<PlagiarismReport | null> {
    try {
      return await this.service.updatePlagiarismReport({
        ...args,
        data: {
          ...args.data,

          document: args.data.document
            ? {
                connect: args.data.document,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PlagiarismReport)
  async deletePlagiarismReport(
    @graphql.Args() args: DeletePlagiarismReportArgs
  ): Promise<PlagiarismReport | null> {
    try {
      return await this.service.deletePlagiarismReport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Document, {
    nullable: true,
    name: "document",
  })
  async getDocument(
    @graphql.Parent() parent: PlagiarismReport
  ): Promise<Document | null> {
    const result = await this.service.getDocument(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
